/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  NftMarketplace,
  NftMarketplaceInterface,
} from "../../NFTMarketplace.sol/NftMarketplace";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "nftId",
        type: "uint256",
      },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "purchasedNFTs",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101a0806100206000396000f3fe6080604052600436106100295760003560e01c806379a513031461002e578063d96a094a1461006b575b600080fd5b34801561003a57600080fd5b50610055600480360381019061005091906100ea565b610087565b6040516100629190610122565b60405180910390f35b610085600480360381019061008091906100ea565b6100a7565b005b60006020528060005260406000206000915054906101000a900460ff1681565b600160008083815260200190815260200160002060006101000a81548160ff02191690831515021790555050565b6000813590506100e481610153565b92915050565b6000602082840312156100fc57600080fd5b600061010a848285016100d5565b91505092915050565b61011c8161013d565b82525050565b60006020820190506101376000830184610113565b92915050565b60008115159050919050565b6000819050919050565b61015c81610149565b811461016757600080fd5b5056fea26469706673582212207f7981d332ba56e82f05be4833408f4a6bbb540f312f55f9a676ae438f34ee0f64736f6c63430008040033";

type NftMarketplaceConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: NftMarketplaceConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class NftMarketplace__factory extends ContractFactory {
  constructor(...args: NftMarketplaceConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<NftMarketplace> {
    return super.deploy(overrides || {}) as Promise<NftMarketplace>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): NftMarketplace {
    return super.attach(address) as NftMarketplace;
  }
  override connect(signer: Signer): NftMarketplace__factory {
    return super.connect(signer) as NftMarketplace__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): NftMarketplaceInterface {
    return new utils.Interface(_abi) as NftMarketplaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): NftMarketplace {
    return new Contract(address, _abi, signerOrProvider) as NftMarketplace;
  }
}
